AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "db/migrate/*"
    - 'config/**/*'
    - "bin/**/*"
  DisplayCopNames: true

## 各設定は基本falseで Trueの場合にメモしておく

## Style 
Style/Alias:
  Enabled: false
Style/AndOr:
  Enabled: true # andよりも&&、orよりも||を推奨
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/SpaceAfterColon:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringMethods:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLitera:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false

## Metrics 
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

## Layout
Layout/IndentationConsistency:
  EnforcedStyle: normal # private/protected はインデントを下げない

## Rails
Rails/SafeNavigation:
  ConvertTry: false
Rails/Delegate:
  Enabled: false
Rails/Blank:
  NilOrEmpty: true # foo.nil? || foo.empty?　は foo.blank?に置き換える
  NotPresent: false
  UnlessPresent: false
